# Generated by Django 4.1.3 on 2022-11-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='this is cool!', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
